### ISSUE TITLE
Error while running grimoirelab-gitee

### ISSUE THREAD

**Issue by ME-Msc** [chaoss/grimoirelab-elk-gitee#2]
I was trying to run gimoirelab-gitee following the wiki [How to run grimoirelab gitee](https://github.com/open-metrics-code/grimoirelab/wiki/How-to-run-grimoirelab-gitee%3F).

**Environment**: Ubuntu18.04, python3.8(ivenv)

**Supports**: 
1. OpenSearch:1.2.0, grimoirelab/hatstall:latest, mariadb:10.0
![docker_ps](https://user-images.githubusercontent.com/45875501/185775643-e0962a18-1683-4468-b7f7-6930d8c6c842.JPG)

2.  grimoirelab-perceval-gitee, grimoirelab-elk-gitee
When I checked with `sudo pip3 list -l`, it showed like the following.
![捕获](https://user-images.githubusercontent.com/45875501/185775719-9152ac4a-3bdf-4f20-8252-5400610c6549.JPG)

**Modify the setting files**
1. /grimoirelab/default-grimoirelab-settings/projects.json
> {
    "gitee-test-repo": {
        "git":[
            "https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee.git"
        ],
        "gitee":[
            "https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee"
        ],
        "gitee:repo":[
            "https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee"
        ],
        "gitee:pull":[
            "https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee"
        ],
        "gitee:issue":[
            "https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee"
        ]
    }
}

2. /grimoirelab/default-grimoirelab-settings/setup-gitee.cfg
Actually I only add one line in section [projects] : `projects_file = ./projects.json`

> [general]
short_name = GrimoireLab
update = true
min_update_delay = 86400
debug = true
logs_dir = /tmp/logs
menu_file = ./menu.yaml
aliases_file = ./aliases.json
[projects]
#projects_file = ./projects-gitee-yehui-all.json
#projects_file = ./projects-gitee-yehui-all-hw.json
#projects_file = ./projects-gitee-yehui-pure-paddle.json
#projects_file = ./projects-gitee-yehui-pure-openGauss.json
#projects_file = ./projects-gitee-yehui-pure-minspore.json
#projects_file = ./projects-gitee-yehui-pure-openeuler-iSulad.json
#projects_file = ./projects-gitee-yehui-pure-openeuler-A-Tune.json
#projects_file = ./projects-gitee-yehui-pure-openeuler-stratovirt.json
#projects_file = ./projects-gitee-yehui-pure-openeuler-kernel.json
#projects_file = ./projects-gitee-yehui-pure-openeuler.json
#projects_file = ./projects-gitee-yehui-all-notensorflow.json
#projects_file = ./projects-gitee-yehui-pure-tensorflow.json
#projects_file = ./projects-gitee-yehui-pure-kernel_liteos_a.json
projects_file = ./projects.json
[es_collection]
url = http://localhost:9200
[es_enrichment]
url = http://localhost:9200
[sortinghat]
host = 127.0.0.1
user = root
password = root
database = demo_sh
load_orgs = true
orgs_file = ./organizations.json
autoprofile = [gitee,git,github]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [./identities.yml]
identities_format = grimoirelab
[panels]
kibiter_default_index = git
kibiter_url = http://localhost:5601
community = true
github-repos = true
[phases]
collection = true
identities = false
enrichment = false
panels = false
[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
category = commit
#studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]
studies = [enrich_demography:git, enrich_onion:git]
from-date = 2020-01-01
[enrich_demography:git]
#[enrich_areas_of_code:git]
#in_index = git_demo_raw
#out_index = git-aoc_demo_enriched
[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash
[gitee]
raw_index = gitee_issues-raw
enriched_index = gitee_issues-enriched
category = issue
api-token = 
sleep-for-rate = true
no-archive = true
studies = [enrich_onion:gitee-issue]
from-date = 2021-06-01
[enrich_onion:gitee-issue]
in_index = gitee_issues-enriched
out_index = gitee_issues_onion-enriched
data_source = gitee_issues
[gitee:pull]
raw_index = gitee_pulls-raw
enriched_index = gitee_pulls-enriched
category = pull_request
api-token = 
sleep-for-rate = true
no-archive = true
studies = [enrich_onion:gitee-pull]
from-date = 2021-06-01
[enrich_onion:gitee-pull]
in_index = gitee_pulls-enriched
out_index = gitee_pulls_onion-enriched
data_source = gitee_pulls
[gitee:repo]
raw_index = gitee_repo-raw
enriched_index = gitee_repo-enriched
category = repository
no-archive = true
api-token = 
sleep-for-rate = true
from-date = 2021-06-01
[github:issue]
raw_index = github_raw
enriched_index = github_enriched
api-token = 
category = issue
sleep-for-rate = true
no-archive = true
studies = [enrich_onion:github]
from-date = 2021-05-01
[enrich_onion:github]
in_index_iss = github_enriched
in_index_prs = github-pull_enriched
out_index_iss = github-issues-onion_enriched
out_index_prs = github-prs-onion_enriched
[github:pull]
raw_index = github-pull_raw
enriched_index = github-pull_enriched
api-token = 
category = pull_request
sleep-for-rate = true
no-archive = true
from-date = 2021-05-01
[github:repo]
raw_index = github-repo_raw
enriched_index = github-repo_enriched
api-token = 
category = repository
sleep-for-rate = true
no-archive = true
from-date = 2021-05-01

**Error**:
When I ran `sirmordred -c setup-gitee.cfg`, the error message showed like the following.
![error](https://user-images.githubusercontent.com/45875501/185775827-377d2b29-252a-4d70-bb10-ecc05b279212.JPG)
I guess sirmordred didn't recognize the section [gitee]. Am I right? 
I tried to check the log file `/tmp/log` which is the logs_dir set in setup-gitee.cfg-[general], but it didn't exist.
What can I do to fix the error? Thanks for your help!!!

**Comment by eyehwan** [comment]
Hi @ME-Msc, you don't configure: 
```
"gitee:issue":[
"https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee"
] 
```
in your project file,   both "gitee" and "gitee:issue" point to the issue as data source

**Comment by ME-Msc** [comment]
Thanks for your help. @eyehwan 
I tried to delete the "gitee:issue" section in projects.json. And it became as the following.

> {
    "gitee-test-repo": {
        "git":[
            "https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee.git"
        ],
        "gitee":[
            "https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee"
        ],
        "gitee:repo":[
            "https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee"
        ],
        "gitee:pull":[
            "https://gitee.com/ME-Msc/test-repo-for-grimoirelab-gitee"
        ]
    }
}

And then I tried to run `sudo sirmordred -c setup-gitee.cfg`, the same error showed again. 
![image](https://user-images.githubusercontent.com/45875501/185827905-f9218557-d240-4e78-b0b3-b32b0501a1df.png)

It seemed the error was not fixed yet.
Are there any other problems of my settings？

**Comment by shanchenqi** [comment]
Hi @ME-Msc, [gitee] is supported by [endpoint](https://github.com/chaoss/grimoirelab-elk/blob/96d31f23d7b60f658876089b819ec3fc5b1adecf/grimoire_elk/utils.py#L279). Could you check the code in compassFiles/repos/grimoireelk/grimoire_elk/utils.py and tell me whether your code is newest?

**Comment by ME-Msc** [comment]
It's the newest. I am going to rebuild it to see whether the error will appear again. Thanks for your help!

**Comment by ME-Msc** [comment]
It's the newest. I am going to rebuild it to see whether the error will appear again. Thanks for your help!

**Comment by ME-Msc** [comment]
Hi @eyehwan @shanchenqi 
I met an error while rebuilding grimoirelab. 
`./build_grimoirelab -l debug --logfile /home/msc/giteeFiles/log \
 --build --install --check --relfile ../releases/latest \
 --reposdir /home/msc/giteeFiles/repos \
 --install_venv /home/msc/giteeFiles/ivenv
`
![image](https://user-images.githubusercontent.com/45875501/186366177-1dbbdaa4-2f1a-4ffe-a8de-bf8f16469d70.png)
![image](https://user-images.githubusercontent.com/45875501/186341538-d982dd18-3b78-42f0-a078-2978f3fe9328.png)

Actually I had met it last time, but I ignored the error. Because I realized grimoirelab-elk would be replaced with grimoirelab-elk-gitee as the wiki [How to run grimoirelab gitee](https://github.com/open-metrics-code/grimoirelab/wiki/How-to-run-grimoirelab-gitee%3F) says.

Can I ignore this error and continue other steps to [install Gitee moudles ](https://github.com/open-metrics-code/grimoirelab/wiki/How-to-run-grimoirelab-gitee%3F#4-install-gitee-modules)?
If not, how can I fix it?

Thanks for your help!

**Comment by ME-Msc** [comment]
Remove "check_run" in [build_grimoirelab#L80](https://github.com/chaoss/grimoirelab/blob/d3dca8d8cb5eb136e23017773716544501e8fd1b/utils/build_grimoirelab#L80)

follow chaoss/grimoirelab#512
